GET http://localhost:9000/tasks

###

GET http://localhost:9000/tasks/5fce43d27c1f661105443d51

###

POST http://localhost:9000/tasks
Content-Type: application/json

{
    "tasklist": [{
        "id": "1111",
        "text": "task 1", 
        "complete": false
    },
    {
        "id": "1112",
        "text": "task 2", 
        "complete": false
    }]
}

### 
DELETE http://localhost:9000/tasks/5fceef27bd197320f7e8a66a

###
PATCH http://localhost:9000/tasks/5fce49fb77423713cb0e0359
Content-Type: application/json

{
    "tasklist": [2, 3, 4]
}